# Generated by Django 5.0.4 on 2024-05-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssm_app', '0009_alter_song_playlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='ssm_app.playlist'),
        ),
    ]
